name: dbc_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
  - assets/json/jogos.json
  - assets/Madmax.jpg
  - assets/Uncharted.jpg
  - assets/MadmaxImg1.jpg
  - assets/MadMaxImg2.jpg
  - assets/MadMaxImg3.jpg
  - assets/MadMaxImg4.jpg
  - assets/MadMaxImg5.jpg
  - assets/NathanDrake.jpg
  - assets/NathanDrake2.jpg
  - assets/NathanDrake3.jpg
  - assets/NathanDrake4.jpg
  - assets/NathanDrake5.jpg